# Generated by Django 5.2 on 2025-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, choices=[('BR', 'Brazilian'), ('US', 'American'), ('MX', 'Mexican'), ('AR', 'Argentinian'), ('CO', 'Colombian'), ('VE', 'Venezuelan'), ('EC', 'Ecuadorian'), ('CL', 'Chilean')], max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
